[package]
name = "ovia-db"
version.workspace = true
edition.workspace = true

[dependencies]
sqlx = { workspace = true }
tracing = { workspace = true }
ovia-common = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
