[package]
name = "ovia-rag"
version.workspace = true
edition.workspace = true

[[bin]]
name = "ovia-rag"
path = "src/main.rs"

[dependencies]
tokio = { workspace = true }
tracing = { workspace = true }
ovia-common = { workspace = true }
ovia-config = { workspace = true }
